### ISSUE TITLE
can not sure raw.githubusercontent.com ip address

### ISSUE THREAD

**Issue by qqqays** [roslovets/AppDesignerPro#1]
wrong use webhead
can not sure raw.githubusercontent.com ip address

when i use the command eval(webread('https://git.io/fjbyL')) at matlab cmd windows

**Comment by roslovets** [comment]
It's strange, because it works perfectly for me:

```MATLAB
eval(webread('https://git.io/fjbyL'))
```

By the way you can manually download latest version from the [Releases page](https://github.com/roslovets/AppDesignerPro/releases):

![image](https://user-images.githubusercontent.com/21337619/103183008-e5b99e80-48c0-11eb-8a01-34b13fce0c46.png)
